### ISSUE TITLE
Option to teleport to location in which report was made.

### ISSUE THREAD

**Issue by sid-engel** [ZeppelinForDays/ReportPlus#1]
Hello there, just installed your plugin.

Could we get an option to teleport to the location that the report was made at? This would be useful for reports of grief, when there are no staff on at the moment to handle it.

Thanks!

**Comment by ZeppelinForDays** [comment]
I really appreciate the suggestion, you can see this implemented in the future release.

**Comment by ZeppelinForDays** [comment]
Implemented. Thank you!
