### ISSUE TITLE
1.15 Support?

### ISSUE THREAD

**Issue by sid-engel** [ZeppelinForDays/ReportPlus#10]
Hey there, could we get some 1.15 support for this plugin? My server still relies heavily on it, and it's been a great service! It seems to load up okay, however errors our upon using any commands

03.02 23:43:00 [Server] INFO Sid_Engel issued server command: /reports
03.02 23:43:00 [Server] ERROR null
03.02 23:43:00 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'reports' in plugin ReportPlus v1.3.2 - plugin is disabled.
03.02 23:43:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820) ~[?:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[?:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-67]
03.02 23:43:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by ZeppelinForDays** [comment]
Plugin has been updated to work on 1.15.2. Thank you for pointing out this problem.
