### ISSUE TITLE
Plugin losing "player reported" data.

### ISSUE THREAD

**Issue by sid-engel** [ZeppelinForDays/ReportPlus#5]
It seems that after a player in which was reported logs off, or a certain amount of time has passed. The data for who was reported is lost, and instead it shows as if the reporter had reported themselves.

Our server restarts every 8 hours, so I'm not sure if it's caused by the restart... More testing to come.

It would be amazing to see mysql support for this.

**Comment by sid-engel** [comment]
https://i.imgur.com/Dp8muIj.png

**Comment by ZeppelinForDays** [comment]
I would like to know if the latest release fixed your issue? Would be very much appreciated.
